!$Id: gckpp_adj_Global.f90,v 1.4 2010/04/01 07:09:43 daven Exp $
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_adj_Global.f90
! Time                 : Mon Jun  8 14:14:29 2009
! Working directory    : /home/kumaresh/GEOS/GEOS-Chem.v8-02-01.stdrun/GC_KPP
! Equation file        : gckpp_adj.kpp
! Output root filename : gckpp_adj
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_adj_Global

  USE gckpp_adj_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  USE MYTYPE
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  TYPE (XPLEX) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  TYPE (XPLEX) :: VAR(NVAR)
  ! VAR - Concentrations of variable species (global)
  TYPE (XPLEX) :: VAR_ADJ(NVAR)
  ! VAR - Concentrations of variable species (global)
  TYPE (XPLEX) :: V_CSPEC(NVAR)
  ! VAR - Concentrations of variable species (global)
  TYPE (XPLEX) :: V_CSPEC_ADJ(NVAR)
! FIX - Concentrations of fixed species (global)
  TYPE (XPLEX) :: FIX(NFIX)
!! dkh: take this out so that VAR can be threadprivate (dkh, 07/28/09) 
! VAR, FIX are chunks of array C
!      EQUIVALENCE( C(1),VAR(1) )
!      EQUIVALENCE( C(91),FIX(1) )
! RCONST - Rate constants (global)
  TYPE (XPLEX) :: RCONST(NREACT)
! TIME - Current integration time
  TYPE (XPLEX) :: TIME
! SUN - Sunlight intensity between [0,1]
  TYPE (XPLEX) :: SUN
! TEMP - Temperature
  TYPE (XPLEX) :: TEMP
! RTOLS - (scalar) Relative tolerance
  TYPE (XPLEX) :: RTOLS
! TSTART - Integration start time
  TYPE (XPLEX) :: TSTART
! TEND - Integration end time
  TYPE (XPLEX) :: TEND
! DT - Integration step
  TYPE (XPLEX) :: DT
! ATOL - Absolute tolerance
  TYPE (XPLEX) :: ATOL(NVAR)
! RTOL - Relative tolerance
  TYPE (XPLEX) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  TYPE (XPLEX) :: STEPMIN
! STEPMAX - Upper bound for integration step
  TYPE (XPLEX) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  TYPE (XPLEX) :: CFACTOR
! DDMTYPE - DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER :: DDMTYPE

! INLINED global variable declarations
  
  ! INLINED global variable declarations

  ! Number of cost function being evaluated
  INTEGER, PARAMETER :: NJ = 1
  
  ! Total number of tropospheric grid cells
  INTEGER :: NTT 

  ! Total number of tropospheric grid cells
  INTEGER :: JLOOP
  
  ! Parameter for insuring positive tracer values, same as in reader.f
  TYPE (XPLEX), PARAMETER  :: SMAL2 = xplex(1.0d-99,0d0)
  TYPE (XPLEX), PARAMETER  :: SMALL2 = xplex(1.0d-99,0d0)
  
  ! Number of reaction rate coeff adjoints
  INTEGER, PARAMETER  :: NCOEFF = 14

  ! VAR_R_ADJ - Concentrations of reaction rate adjoint (global)
  TYPE (XPLEX) :: VAR_R_ADJ(NCOEFF)
  
  ! Reaction numbers for each (define in INIT_KPP)
  INTEGER             :: JCOEFF(NCOEFF)
  INTEGER             :: IND(NREACT)

! INLINED global variable declarations

! Need to declare these THREADPRIVATE for OMP parallelization (dkh, 07/28/09) 
!$OMP THREADPRIVATE( JLOOP ) 
!$OMP THREADPRIVATE( C   ) 
!$OMP THREADPRIVATE( VAR ) 
!$OMP THREADPRIVATE( VAR_ADJ ) 
!$OMP THREADPRIVATE( FIX )
!$OMP THREADPRIVATE( V_CSPEC ) 
!$OMP THREADPRIVATE( V_CSPEC_ADJ ) 
!$OMP THREADPRIVATE( TIME )
!$OMP THREADPRIVATE( VAR_R_ADJ ) 
!$OMP THREADPRIVATE( RCONST )

! Move stack_ptr here and make THREADPRIVATE for OMP parallelization (dkh, 07/28/09) 
  INTEGER :: stack_ptr = 0 ! last written entry
!$OMP THREADPRIVATE( stack_ptr )

 INTEGER :: DMAP(NCOEFF)

END MODULE gckpp_adj_Global

