!$Id: gckpp_adj_Rates.f90,v 1.2 2009/06/12 01:44:48 daven Exp $
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_adj_Rates.f90
! Time                 : Mon Jun  8 14:14:29 2009
! Working directory    : /home/kumaresh/GEOS/GEOS-Chem.v8-02-01.stdrun/GC_KPP
! Equation file        : gckpp_adj.kpp
! Output root filename : gckpp_adj
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_adj_Rates

  USE gckpp_adj_Parameters
  USE gckpp_adj_Global
  USE MYTYPE
  USE COMPLEXIFY
  IMPLICIT NONE

CONTAINS

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )

  USE COMODE_MOD,        ONLY : R_KPP
  USE gckpp_adj_Monitor      
  
  INTEGER :: N
  
  DO N = 1, NREACT
     RCONST(N) = R_KPP(JLOOP,IND(N))
  ENDDO
  
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


END MODULE gckpp_adj_Rates

