        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 26 14:19:46 2012
        MODULE LCSTRING__genmod
          INTERFACE 
            SUBROUTINE LCSTRING(STRING)
              CHARACTER(*), INTENT(INOUT) :: STRING
            END SUBROUTINE LCSTRING
          END INTERFACE 
        END MODULE LCSTRING__genmod
