        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 26 14:19:48 2012
        MODULE LEN_STRING__genmod
          INTERFACE 
            FUNCTION LEN_STRING(STR)
              CHARACTER(*) :: STR
              INTEGER(KIND=4) :: LEN_STRING
            END FUNCTION LEN_STRING
          END INTERFACE 
        END MODULE LEN_STRING__genmod
