        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 26 14:19:48 2012
        MODULE LIDORT_STATUS__genmod
          INTERFACE 
            SUBROUTINE LIDORT_STATUS(THREAD,ERRORFILE,ERRORUNIT,        &
     &OPENFILEFLAG,STATUS_INPUTCHECK,NCHECKMESSAGES,CHECKMESSAGES,      &
     &ACTIONS,STATUS_CALCULATION,MESSAGE,TRACE_1,TRACE_2,TRACE_3)
              INTEGER(KIND=4), INTENT(IN) :: THREAD
              CHARACTER(*), INTENT(IN) :: ERRORFILE
              INTEGER(KIND=4), INTENT(IN) :: ERRORUNIT
              LOGICAL(KIND=4), INTENT(INOUT) :: OPENFILEFLAG
              INTEGER(KIND=4), INTENT(IN) :: STATUS_INPUTCHECK
              INTEGER(KIND=4), INTENT(IN) :: NCHECKMESSAGES
              CHARACTER(*), INTENT(IN) :: CHECKMESSAGES(0:25)
              CHARACTER(*), INTENT(IN) :: ACTIONS(0:25)
              INTEGER(KIND=4), INTENT(IN) :: STATUS_CALCULATION
              CHARACTER(*), INTENT(IN) :: MESSAGE
              CHARACTER(*), INTENT(IN) :: TRACE_1
              CHARACTER(*), INTENT(IN) :: TRACE_2
              CHARACTER(*), INTENT(IN) :: TRACE_3
            END SUBROUTINE LIDORT_STATUS
          END INTERFACE 
        END MODULE LIDORT_STATUS__genmod
