        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 26 14:19:48 2012
        MODULE XERBLA__genmod
          INTERFACE 
            SUBROUTINE XERBLA(SRNAME,INFO)
              CHARACTER(LEN=6) :: SRNAME
              INTEGER(KIND=4) :: INFO
            END SUBROUTINE XERBLA
          END INTERFACE 
        END MODULE XERBLA__genmod
