        !COMPILER-GENERATED INTERFACE MODULE: Mon Mar 26 14:19:48 2012
        MODULE XFINDPAR_NOG__genmod
          INTERFACE 
            FUNCTION XFINDPAR_NOG(NUNIT,PARNAME)
              INTEGER(KIND=4) :: NUNIT
              CHARACTER(*) :: PARNAME
              LOGICAL(KIND=4) :: XFINDPAR_NOG
            END FUNCTION XFINDPAR_NOG
          END INTERFACE 
        END MODULE XFINDPAR_NOG__genmod
